seed_everything: 7
trainer:
  checkpoint_callback: true
  callbacks:
    - class_path: pytorch_lightning.callbacks.LearningRateMonitor
      init_args:
        logging_interval: epoch
    - class_path: pytorch_lightning.callbacks.ModelCheckpoint
      init_args:
        save_top_k: 1
        monitor: val_ExpRate
        mode: max
        filename: '{epoch}-{val_loss}-{step}-{val_ExpRate:.4f}'
  # gpus: 1
  gpus: 2 # 1, 2, 3
  accelerator: ddp
  check_val_every_n_epoch: 5 # 5
  max_epochs: 50
  deterministic: true



model:
  d_model: 256
  #encoder
  requires_grad: true
  drop_rate: 0.
  proj_drop_rate: 0.
  attn_drop_rate: 0.
  drop_path_rate: 0.1
  # decoder
  nhead: 8
  num_decoder_layers: 3
  dim_feedforward: 1024
  dropout: 0.3
  dc: 32
  cross_coverage: true
  self_coverage: true
  # beam search
  beam_size: 10
  max_len: 200
  alpha: 1.0
  early_stopping: true
  temperature: 1.0
  # training
  learning_rate: 0.2
  patience: 4
data:
  zipfile_path: data.zip
  test_year: "2014"
  train_batch_size: 8
  eval_batch_size: 4
  num_workers: 4
  scale_aug: false
